events {
    worker_connections 1024;
}

http {
    # Basis instellingen
    server_names_hash_bucket_size 128;
    
    # MIME-types laden (standaard voor Nginx)
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Optimalisaties voor snelheid & efficientie
    sendfile on;
    keepalive_timeout 65;

    # IMPORT: Dit laadt automatisch alle team/functionaliteit bestanden
    # Zorg dat de bestanden in /etc/nginx/conf.d/ eindigen op .conf
    include /etc/nginx/conf.d/*.conf;

    # Fallback server voor ongedefinieerde hostnames
    server {
        listen 30098 ssl;
        server_name _;

        include snippets/ssl-params.conf;

        return 404;
    }
}