upstream billing-ui { server facturatie:80; }
upstream mailing-ui { server mailing:3000; }

server {
    listen 30098 ssl;
    server_name facturatie.integration-project-2026-groep-2.my.be;
    include snippets/ssl-params.conf;
    include snippets/proxy-headers.conf;
    location / {
        auth_basic "Facturatie Area";
        auth_basic_user_file /etc/nginx/.htpasswd-facturatie;
        proxy_pass http://billing-ui/;
    }
}

server {
    listen 30098 ssl;
    server_name mailing.integration-project-2026-groep-2.my.be;
    include snippets/ssl-params.conf;
    include snippets/proxy-headers.conf;
    location / {
        auth_basic "Mailing Area";
        auth_basic_user_file /etc/nginx/.htpasswd-mailing;
        proxy_pass http://mailing-ui/;
    }
}