upstream billing_ui { server billing_app:80; }
upstream mailing_ui { server mailing_app:3000; }

server {
    listen 30098 ssl;
    server_name facturatie.integration-project-2026-groep-2.my.be;
    include snippets/ssl-params.conf;
    include snippets/proxy-headers.conf;
    location / {
        auth_basic "Facturatie Area";
        auth_basic_user_file /etc/nginx/.htpasswd-facturatie;
        proxy_pass http://billing_ui/;
    }
}

server {
    listen 30098 ssl;
    server_name mailing.integration-project-2026-groep-2.my.be;
    include snippets/ssl-params.conf;
    include snippets/proxy-headers.conf;
    location / {
        auth_basic "Mailing Area";
        auth_basic_user_file /etc/nginx/.htpasswd-mailing;
        proxy_pass http://mailing_ui/;
    }
}