upstream control_room_ui {
    server kibana:5601;
}

server {
    listen 30098 ssl;
    server_name control-room.integration-project-2026-groep-2.my.be;
    include snippets/ssl-params.conf;
    include snippets/proxy-headers.conf;

    location / {
        # auth_basic "Control Room Area";
        # auth_basic_user_file /etc/nginx/.htpasswd-control-room;
        proxy_pass http://control_room_ui/;
        proxy_set_header x-found-cluster http://elasticsearch:9200;
    }
}
