upstream frontend_ui {
    server frontend_drupal:80;
}

server {
    listen 30098 ssl;
    server_name www.integration-project-2026-groep-2.my.be;

    include snippets/ssl-params.conf;
    include snippets/proxy-headers.conf;

    location / {
        proxy_pass http://frontend_ui/;
    }
}

server {
    listen 30098 ssl;
    server_name integration-project-2026-groep-2.my.be;

    include snippets/ssl-params.conf;
    include snippets/proxy-headers.conf;

    # Redirect all non-www requests to www
    return 301 https://www.integration-project-2026-groep-2.my.be$request_uri;
}