upstream iot-badge-scanner {
    server iot-badge-scanner:30071;
}

server {
    listen 30098 ssl;
    server_name iot-badge-scanner.integration-project-2026-groep-2.my.be;
    include snippets/ssl-params.conf;
    include snippets/proxy-headers.conf;

    location / {
        proxy_pass http://iot-badge-scanner;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}