ssl_certificate /etc/nginx/certs/integration-project-2026-groep-2.my.be.pem;
ssl_certificate_key /etc/nginx/certs/integration-project-2026-groep-2.my.be.key;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;